### ISSUE TITLE
Got {"message":"Missing Authentication Token" Error When Running Test

### ISSUE THREAD

**Issue by GitHubDiom** [umbrellerde/functionfusion#1]
Dear Authors,

I greatly appreciate your efforts on this insightful work!

I am trying to run the test, and while deploying functions and S3 buckets went smoothly, I encountered an issue when invoking the API Gateway. Specifically, when I use the following curl command:

```bash
curl -X POST https://[baseUrlFromTerraform].execute-api.eu-central-1.amazonaws.com/onlyStage/SYNC-A -H 'Content-Type: application/json' -d '{"sync": true}'
```
I receive the error: `{"message":"Missing Authentication Token"}`.

I am new to the AWS Lambda platform and would greatly appreciate any guidance on resolving this issue.

Thank you so much for your help!

Best regards

**Comment by umbrellerde** [comment]
Hi,

thanks for your interest in Fusionize! I have finally gotten around to updating the main branch to point to the updated version of the source code that was used in the extended version of the paper, sorry for the delay.

Regarding your error, this usually happens when the Base URL from API Gateway is not correct. To me, this happened sometimes when I was not copying the output from terraform correctly. Another reason might be that the code has an implicit assumption that there is only one API Gateway deployed in your account, which it will use (unfortunately I did not find an easy way around this). If you have more than one API Gateway deployed you could test manually deleting the other ones or setting the correct URL manually.

Greetings

**Comment by umbrellerde** [comment]
🤦 nvm I fixed it. The default use case was the IoT use case, which does not have "A" as task. I changed the default use case to "split", so now your call should work.

**Comment by GitHubDiom** [comment]
Thanks for the updating, however, now I got a new error.

command `terraform apply -auto-approve` got the following error.
Is this new version works fine in your env?

```bash
...
╷
│ Error: a number is required
│ 
│   with aws_api_gateway_rest_api.api,
│   on main.tf line 139, in resource "aws_api_gateway_rest_api" "api":
│  139: resource "aws_api_gateway_rest_api" "api" {
│ 
╵
╷
│ Error: Error in function call
│ 
│   on fusionfunction/main.tf line 114, in resource "aws_s3_object" "lambda_fusion_manager":
│  114:   etag   = filemd5(data.archive_file.source_code_archive.output_path)
│     ├────────────────
│     │ while calling filemd5(path)
│     │ data.archive_file.source_code_archive.output_path is "./deployment_artifacts/function.zip"
│ 
│ Call to function "filemd5" failed: open deployment_artifacts/function.zip: no such file or directory.
```

**Comment by umbrellerde** [comment]
Hi, thanks for catching this, I updated the main branch. I commited my zip files, they will be overridden by the zips created by your terraform. It worked for me since my env already has zip files from older runs :)

**Comment by GitHubDiom** [comment]
Thank you so much! It works perfectly!

I have a quick question regarding the design of Fusionize. Does Fusionize dynamically tune the function group based on certain system metrics? It wasn't explicitly mentioned in your Fusionize++ paper.

**Comment by umbrellerde** [comment]
Hi, you can take a look at how the optimizer works in `managers/optimizer`. It basically reads all metrics that were extracted with `managers/extractor` and then comes up with the next group to try. In this prototype, the optimizer is called after 1000 invocations (see e.g. `evalScripts/split/generateConfigurations/doTestrun.sh` for how exactly this works). Hope this helps!

**Comment by GitHubDiom** [comment]
Thanks a lot
